version: '3.8'
services:

  app:
    build:
      context: app
      args:
        PYTHON_VERSION: $APP_PYTHON_VERSION
    environment:
      FLASK_ENV: $ENV
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_DATABASE: $DB_DATABASE
      DB_HOST: "db"
      DB_PORT: $DB_PORT
    ports:
      - target: 5000
        published: $APP_PORT
        mode: host

  db:
    image: postgres:$DB_VERSION
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_DATABASE
    ports:
      - target: 5432
        published: $DB_PORT
        mode: host
    volumes:
      - db_data:/var/lib/postgresql/data

  db_admin:
    image: dpage/pgadmin4:$DB_ADMIN_VERSION
    environment:
      PGADMIN_DEFAULT_EMAIL: $DB_ADMIN_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $DB_ADMIN_PASSWORD
    ports:
      - target: 80
        published: $DB_ADMIN_PORT
        mode: host
    depends_on:
      - db
    volumes:
      - db_admin_data:/var/lib/pgadmin

volumes:
  db_data:
  db_admin_data:
